version: '2'

services:
  app:
    image: 'pdstm'
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - DATASOURCE_DRIVER=${DATASOURCE_DRIVER}
      - DATASOURCE_URL=${DATASOURCE_URL}
      - DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_PROTOCOL=${MAIL_PROTOCOL}
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_HOST=${SERVER_HOST}
      - THREAT_MODEL_FOLDER=${THREAT_MODEL_FOLDER}

  db:
    image: 'postgres:13.1-alpine'
    ports:
      - ${DATASOURCE_PORT}:${DATASOURCE_PORT}
    container_name: db
    environment:
      - POSTGRES_USER=${DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${DATASOURCE_PASSWORD}