spring:
  datasource:
    driver-class-name: ${DATASOURCE_DRIVER}
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

mail:
  host: ${MAIL_HOST}
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
  port: ${MAIL_PORT}
  protocol: ${MAIL_PROTOCOL}

server:
  port: ${SERVER_PORT}
  host: ${SERVER_HOST}"

logging:
  level:
    org:
      jooq:
        tools:
          LoggerListener: DEBUG

threatModelFolder: ${THREAT_MODEL_FOLDER}